# Generated by Django 6.1.1 on 2026-09-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('problem_statement', models.TextField()),
                ('solution', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=15)),
                ('project_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('ACADEMIC', 'Academic'), ('OPEN_SOURCE', 'Open Source'), ('CLIENT', 'Client')], default='PERSONAL', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
