# Generated by Django 6.1.1 on 2026-09-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('GIF', 'Gif'), ('PDF', 'Pdf'), ('OTHER', 'Other')], default='IMAGE', max_length=15)),
                ('alt_text', models.CharField(max_length=300, null=True)),
                ('caption', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('type', models.CharField(choices=[('LANGUAGE', 'Language'), ('FRAMEWORK', 'Framework'), ('LIBRARY', 'Library'), ('DATABASE', 'Database'), ('PLATFORM', 'Platform'), ('RUNTIME', 'Runtime'), ('OTHER', 'Other'), ('TOOLS', 'Tools')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution',
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='motivation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.ManyToManyField(related_name='projects', to='project.media'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='project.skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='project.technology'),
        ),
    ]
