# Generated by Django 6.1.1 on 2026-09-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_media_skill_technology_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media_tools',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
